export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD_COUNTER = 'ADD_COUNTER';
export const SUBTRACT_COUNTER = 'SUBTRACT_COUNTER';
export const DELETE_RESULT = 'DELETE_RESULT'
export const STORE_RESULT = 'STORE_RESULT'